### ISSUE TITLE
Outline fonts in SVG export

### ISSUE THREAD

**Issue by owenmcg** [rossburton/mausritter-item-cards#12]
When pulling the SVG into InDesign I got a ‘missing font’ error in the Pre-flight panel. Would it be possible to get an SVG export where the fonts were outlined? Just to save installing the relevant fonts.

**Comment by rossburton** [comment]
Not sure that would be an option with the font license. A workaround is to press the Use Free Fonts button.

**Comment by owenmcg** [comment]
Thanks Ross. The generator is really cool 👍 Thanks for sharing it.
